### ISSUE TITLE
mysql container --default-authentication-plugin command 

### ISSUE THREAD

**Issue by Ataa55** [ahmedsami76/relational-databases#7]
starting from version 8.4 this command isn't available "--default-authentication-plugin=mysql_native_password", so setting the version to the latest will not work, i went with version 8.3 and it worked will.

**Comment by ihendawi** [comment]
@Ataa55  
Remove the `command: --default-authentication-plugin=mysql_native_password` line from docker-compose.yml
and it will work on mysql:latest clearly.
MySQL 8.0+ uses a different authentication mechanism, and the native password plugin may not be required.
